stages:
  - build
  - deploy

before_script:
  - export TAG=${CI_COMMIT_SHA:0:8}
  - export BRANCH=${CI_COMMIT_REF_NAME}
  - export REGISTRY_HOST=${CI_REGISTRY}
  - export REGISTRY_URI="/${CI_PROJECT_PATH}"
  - touch .env.development
  - touch .env.production

build:
  stage: build
  script:
    - docker info
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker-compose build --pull web
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker-compose push web
  tags:
    - local

staging:
  stage: deploy
  
  variables:
    NAMESPACE: staging
  script:
    - export KUBECONFIG=$KUBECONFIG_ATLA
    - "keybase status | grep 'Logged in:     no' && keybase oneshot"
    - ./chart/bin/decrypt staging
    - ./chart/bin/deploy omeka $CI_COMMIT_SHORT_SHA staging-values.yaml
  after_script:
    - rm -f ./chart/*-values.yaml
    - keybase logout
  when: manual
  tags:
    - local

production:
  stage: deploy
  
  variables:
    NAMESPACE: production
  script:
    - export KUBECONFIG=$KUBECONFIG_ATLA
    - "keybase status | grep 'Logged in:     no' && keybase oneshot"
    - ./chart/bin/decrypt production
    - ./chart/bin/deploy omeka  $CI_COMMIT_SHORT_SHA production-values.yaml
  after_script:
    - rm -f ./chart/*-values.yaml
    - keybase logout
  when: manual
  tags:
    - local
